/**
 * 模擬api SPEC11080101-投資交易明細
 */

let dataToday = {
    "apiId": "SPEC11080101",
    "token": {
        "requestId": "",
        "responseTime": "2020-07-13 13:24:21",
        "lang": "zh_TW"
    },
    "resFlag": "0",
    "resMessage": {
        "errorCode": "",
        "errorMsg": ""
    },
    "resContent": {
        'paginator': {
            'totalCount': '30',
            'pageSize': '5',
            'pageNumber': '2',
            'sortColName': '',
            'sortDirection': 'ASC'
        },
        "vecPtib08": [
            {
                "trustNo": "07109000005",
                "fund": "FF01",
                "amt": "100,000.00",
                "acctDate": "",
                "fundName": "野村美美現",
                "acctCcy": "",
                "lastIntCcy": "USD",
                "txDate": "109/02/15",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "30.0500",
                "encodeTrustNo": "RG01WDJsUWRuekg0ZmFoY0M4SmxQQT09VyYkIyFBblNFTnZjVTdhTDg9",
                "fee": "",
                "lastIntChiccy": "美金",
                "value": "",
                "txType": "1",
                "txTypeName": "申購",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "申購尚未分配",
                "sort": "1090215",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000004",
                "fund": "9601",
                "amt": "100,000.00",
                "acctDate": "",
                "fundName": "柏瑞高台配",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/17",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "20.0200",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "5",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090217",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000003",
                "fund": "9802",
                "amt": "90,000.00",
                "acctDate": "",
                "fundName": "柏瑞高台配",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/18",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "25.0320",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "2",
                "txTypeName": "轉出",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "轉出尚未分配",
                "sort": "1090218",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000002",
                "fund": "9752",
                "amt": "95,000.00",
                "acctDate": "",
                "fundName": "雅詩羅特高債券型基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/17",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "25.7500",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "3",
                "txTypeName": "轉入",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "轉入尚未分配",
                "sort": "1090217",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000001",
                "fund": "9425",
                "amt": "85,000.00",
                "acctDate": "",
                "fundName": "富蘭特林配息基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/15",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "32.580",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "4",
                "txTypeName": "贖回",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "贖回尚未分配",
                "sort": "1090215",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07308000090",
                "fund": "9432",
                "amt": "75,000.00",
                "acctDate": "",
                "fundName": "富達東南亞",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "28.950",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "5",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090214",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000089",
                "fund": "9365",
                "amt": "85,000.00",
                "acctDate": "",
                "fundName": "匯豐龍鳳基金Ａ類型",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/13",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "48.650",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "6",
                "txTypeName": "除權",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除權尚未分配",
                "sort": "1090213",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000074",
                "fund": "9256",
                "amt": "78,000.00",
                "acctDate": "",
                "fundName": "景順全歐洲企業基金歐元",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/12",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "450.260",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "2",
                "txTypeName": "轉出",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "轉出尚未分配",
                "sort": "1090212",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000066",
                "fund": "9646",
                "amt": "42,000.00",
                "acctDate": "",
                "fundName": "匯豐龍鳳基金B類型",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/11",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "62.780",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "1",
                "txTypeName": "申購",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "申購尚未分配",
                "sort": "1090211",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            }
        ],
        "oneYearAgoDate": "1080713"
    }
}

let data7D = {
    "apiId": "SPEC11080101",
    "token": {
        "requestId": "",
        "responseTime": "2020-07-13 13:24:21",
        "lang": "zh_TW"
    },
    "resFlag": "0",
    "resMessage": {
        "errorCode": "",
        "errorMsg": ""
    },
    "resContent": {
        'paginator': {
            'totalCount': '30',
            'pageSize': '5',
            'pageNumber': '2',
            'sortColName': '',
            'sortDirection': 'ASC'
        },
        "vecPtib08": [
            {
                "trustNo": "07109000069",
                "fund": "7785",
                "amt": "58,000.00",
                "acctDate": "",
                "fundName": "匯豐成功基金",
                "acctCcy": "",
                "lastIntCcy": "USD",
                "txDate": "109/02/15",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "24.0500",
                "encodeTrustNo": "RG01WDJsUWRuekg0ZmFoY0M4SmxQQT09VyYkIyFBblNFTnZjVTdhTDg9",
                "fee": "",
                "lastIntChiccy": "美金",
                "value": "",
                "txType": "1",
                "txTypeName": "申購",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "申購尚未分配",
                "sort": "1090215",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000004",
                "fund": "9601",
                "amt": "100,000.00",
                "acctDate": "",
                "fundName": "摩根太平洋證券基金美元",
                "acctCcy": "",
                "lastIntCcy": "USD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "88.2180",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "美金",
                "value": "",
                "txType": "3",
                "txTypeName": "轉入",
                "chiccy": "美金",
                "acctAmt": "",
                "memo": "轉入尚未分配",
                "sort": "1090214",
                "ccy": "USD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000071",
                "fund": "9846",
                "amt": "65,000.00",
                "acctDate": "",
                "fundName": "ＪＰＭ亞太入息基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/19",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "67.280",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "日幣",
                "value": "",
                "txType": "4",
                "txTypeName": "贖回",
                "chiccy": "日幣",
                "acctAmt": "",
                "memo": "贖回尚未分配",
                "sort": "1090219",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000002",
                "fund": "9752",
                "amt": "62,000.00",
                "acctDate": "",
                "fundName": "雅詩羅特高債券型基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/13",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "55.9500",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "5",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090213",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000081",
                "fund": "9378",
                "amt": "85,000.00",
                "acctDate": "",
                "fundName": "匯豐龍鳳基金C類型",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/11",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "40.2650",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "6",
                "txTypeName": "除權",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除權尚未分配",
                "sort": "1090211",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07308000090",
                "fund": "9432",
                "amt": "75,000.00",
                "acctDate": "",
                "fundName": "富達東南亞",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "48.6500",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "5",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090214",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000089",
                "fund": "9365",
                "amt": "85,000.00",
                "acctDate": "",
                "fundName": "匯豐龍鳳基金Ａ類型",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/13",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "47.5600",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "6",
                "txTypeName": "除權",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除權尚未分配",
                "sort": "1090213",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000074",
                "fund": "9279",
                "amt": "59,000.00",
                "acctDate": "",
                "fundName": "摩根東協基金美元",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "4",
                "txTypeName": "贖回",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "贖回尚未分配",
                "sort": "1090214",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000085",
                "fund": "9695",
                "amt": "38,000.00",
                "acctDate": "",
                "fundName": "摩根泰國基金美元",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/11",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "1",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090211",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            }
        ],
        "oneYearAgoDate": "1080713"
    }
};
let data1M = {
    "apiId": "SPEC11080101",
    "token": {
        "requestId": "",
        "responseTime": "2020-07-13 13:24:21",
        "lang": "zh_TW"
    },
    "resFlag": "0",
    "resMessage": {
        "errorCode": "",
        "errorMsg": ""
    },
    "resContent": {
        'paginator': {
            'totalCount': '30',
            'pageSize': '5',
            'pageNumber': '2',
            'sortColName': '',
            'sortDirection': 'ASC'
        },
        "vecPtib08": [
            {
                "trustNo": "07109000058",
                "fund": "7959",
                "amt": "74,000.00",
                "acctDate": "",
                "fundName": "摩根東協基金美元",
                "acctCcy": "",
                "lastIntCcy": "USD",
                "txDate": "109/02/16",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "26.0500",
                "encodeTrustNo": "RG01WDJsUWRuekg0ZmFoY0M4SmxQQT09VyYkIyFBblNFTnZjVTdhTDg9",
                "fee": "",
                "lastIntChiccy": "轉出",
                "value": "",
                "txType": "2",
                "txTypeName": "轉出",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "轉出尚未分配",
                "sort": "1090216",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000048",
                "fund": "9462",
                "amt": "62,000.00",
                "acctDate": "",
                "fundName": "貝萊德投信",
                "acctCcy": "",
                "lastIntCcy": "USD",
                "txDate": "109/02/12",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "49.7500",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "美金",
                "value": "",
                "txType": "3",
                "txTypeName": "轉入",
                "chiccy": "美金",
                "acctAmt": "",
                "memo": "轉入尚未分配",
                "sort": "1090212",
                "ccy": "USD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000071",
                "fund": "4526",
                "amt": "65,000.00",
                "acctDate": "",
                "fundName": "ＪＰＭ日本（日圓）基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "49.280",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "日幣",
                "value": "",
                "txType": "4",
                "txTypeName": "除息",
                "chiccy": "日幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090214",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000049",
                "fund": "9752",
                "amt": "51,000.00",
                "acctDate": "",
                "fundName": "雅詩羅特高債券型基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/15",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "46.7800",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "5",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090215",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000084",
                "fund": "9194",
                "amt": "67,000.00",
                "acctDate": "",
                "fundName": "摩根太平洋證券基金美元",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/13",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "38.2650",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "6",
                "txTypeName": "除權",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除權尚未分配",
                "sort": "1090213",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07308000074",
                "fund": "9726",
                "amt": "55,000.00",
                "acctDate": "",
                "fundName": "富達東南亞",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "65.6500",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "5",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090214",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000089",
                "fund": "9365",
                "amt": "85,000.00",
                "acctDate": "",
                "fundName": "匯豐龍鳳基金Ａ類型",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/16",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "47.5600",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "6",
                "txTypeName": "申購",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "申購尚未分配",
                "sort": "1090216",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000074",
                "fund": "9279",
                "amt": "59,000.00",
                "acctDate": "",
                "fundName": "摩根東協基金美元",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "4",
                "txTypeName": "贖回",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "贖回尚未分配",
                "sort": "1090214",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000049",
                "fund": "9542",
                "amt": "49,000.00",
                "acctDate": "",
                "fundName": "匯豐誠忠基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/16",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "1",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090216",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            }
        ],
        "oneYearAgoDate": "1080713"
    }
};
let dataCustom = {
    "apiId": "SPEC11080101",
    "token": {
        "requestId": "",
        "responseTime": "2020-07-13 13:24:21",
        "lang": "zh_TW"
    },
    "resFlag": "0",
    "resMessage": {
        "errorCode": "",
        "errorMsg": ""
    },
    "resContent": {
        'paginator': {
            'totalCount': '30',
            'pageSize': '5',
            'pageNumber': '2',
            'sortColName': '',
            'sortDirection': 'ASC'
        },
        "vecPtib08": [
            {
                "trustNo": "07109000045",
                "fund": "7995",
                "amt": "64,000.00",
                "acctDate": "",
                "fundName": "匯豐成功基金",
                "acctCcy": "",
                "lastIntCcy": "USD",
                "txDate": "109/02/14",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "48.0500",
                "encodeTrustNo": "RG01WDJsUWRuekg0ZmFoY0M4SmxQQT09VyYkIyFBblNFTnZjVTdhTDg9",
                "fee": "",
                "lastIntChiccy": "贖回",
                "value": "",
                "txType": "4",
                "txTypeName": "贖回",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "贖回尚未分配",
                "sort": "1090214",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000045",
                "fund": "9462",
                "amt": "51,000.00",
                "acctDate": "",
                "fundName": "貝萊德投信",
                "acctCcy": "",
                "lastIntCcy": "USD",
                "txDate": "109/02/11",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "95.7500",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "美金",
                "value": "",
                "txType": "3",
                "txTypeName": "轉入",
                "chiccy": "美金",
                "acctAmt": "",
                "memo": "轉入尚未分配",
                "sort": "1090211",
                "ccy": "USD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000069",
                "fund": "4526",
                "amt": "65,000.00",
                "acctDate": "",
                "fundName": "匯豐龍鳳基金C類型",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/12",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "49.280",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "4",
                "txTypeName": "贖回",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "贖回尚未分配",
                "sort": "1090212",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000047",
                "fund": "9752",
                "amt": "51,000.00",
                "acctDate": "",
                "fundName": "雅詩羅特高債券型基金",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/11",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "81.7800",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "1",
                "txTypeName": "申購",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "申購尚未分配",
                "sort": "1090211",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000082",
                "fund": "9178",
                "amt": "46,000.00",
                "acctDate": "",
                "fundName": "匯豐中華投信",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/19",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "38.2650",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "4",
                "txTypeName": "贖回",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "贖回尚未分配",
                "sort": "1090219",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07308000059",
                "fund": "9744",
                "amt": "94,000.00",
                "acctDate": "",
                "fundName": "富達東南亞",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/16",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "65.6500",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "5",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090216",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000067",
                "fund": "9920",
                "amt": "48,000.00",
                "acctDate": "",
                "fundName": "台新投信",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/17",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "47.5600",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "1",
                "txTypeName": "申購",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "申購尚未分配",
                "sort": "1090217",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000065",
                "fund": "9456",
                "amt": "47,000.00",
                "acctDate": "",
                "fundName": "趙易投信",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/18",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "25.9520",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "1",
                "txTypeName": "申購",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "申購尚未分配",
                "sort": "1090218",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            },
            {
                "trustNo": "07309000041",
                "fund": "9586",
                "amt": "36,000.00",
                "acctDate": "",
                "fundName": "順益投信",
                "acctCcy": "",
                "lastIntCcy": "TWD",
                "txDate": "109/02/11",
                "lastInt": ".00",
                "chgDate": "",
                "unit": "",
                "exRate": "",
                "encodeTrustNo": "bGdXMC9haWhHeFdja3hKNzJBa1dMdz09VyYkIyFBdU5sWWZVODhwWG89",
                "fee": "",
                "lastIntChiccy": "台幣",
                "value": "",
                "txType": "1",
                "txTypeName": "除息",
                "chiccy": "台幣",
                "acctAmt": "",
                "memo": "除息尚未分配",
                "sort": "1090211",
                "ccy": "TWD",
                "applyRate": "",
                "acctChiccy": ""
            }
        ],
        "oneYearAgoDate": "1080713"
    }
};
let dataEmpty = {
    apiId: "SPEC11060101",
    token: {
        requestId: "",
        responseTime: "2020-07-17 11:13:27",
        lang: "zh_TW"
    },
    resFlag: '0',
    resMessage: {
        errorCode: "",
        errorMsg: ""
    },
    resContent: {
        outputData: [
            {
                isNetTrans: "true",
                roiDataList: [

                ],
                "infoDateStr": "2020/07/17  11：13：27  AM"
            }
        ]
    }
};

let df_response = {};

export const api_response = { ...df_response, ...dataToday };
export const api_response7D = { ...df_response, ...data7D };
export const api_response1M = { ...df_response, ...data1M };
export const api_responseCustom = { ...df_response, ...dataCustom };
export const api_empty = { ...df_response, ...dataEmpty };
export const api_error = {
    apiId: 'SPEC11060101',
    token: {
        requestId: '',
        responseTime: '2020-06-20 18:18:31',
        lang: 'zh_TW'
    },
    resFlag: '1',
    resMsg: {
        errorCode: 'ERRAAAAAAA',
        errorMsg: 'Test Error'
    }
};
export const api_exception = {
    errorCode: 'ERRAAAAAAA',
    errorMsg: 'Test Error'
};
