export const Request_template = {
  CCMPTX000001Rq: { "TxnId": "", "PushToken": "" },
  CCMPTX000002Rq: { "TxnId": "" },
  CCMPTX000003Rq: { "TxnId": "", "Country": "", "Locale": "", "BulletinId":"" },
  CCMPTX000004Rq: { "TxnId": "", "NotifySeq": "" },
  CCMPTX000005Rq: { "TxnId": "", "SystemId": "", "Country": "", "CompanyId": "", "UserId": "", "Password": "", "PasswordE2EE": "", "AuthType": "" },
  CCMPTX000005Rq1: { "TxnId": "", "SystemId": "", "Country": "", "CompanyId": "", "UserId": "", "Password": "", "AuthType": "" },
  CCMPTX000005Rq2: { "TxnId": "", "SystemId": "", "Country": "", "CompanyId": "", "UserId": "", "Password": "", "AuthType": "" },
  CCMPTX000005Rq3: { "TxnId": "", "SystemId": "", "Country": "", "CompanyId": "", "UserId": "", "Password": "", "AuthType": "" },
  CCMPTX000006Rq: { "TxnId": "", "ActivateCode": "" },
  CCMPTX000007Rq: { "TxnId": "", "InitialData": "", "PushToken": "" },
  CCMPTX000008Rq: { "TxnId": "", "AuthenticationCode": "" },
  CCMPTX000009Rq: { "TxnId": "", "OrgPassword": "", "NewPassword": "", "PasswordE2EE": "" },
  CCMPTX000011Rq: { "TxnId": "" },
  CCMPTX000012Rq: { "TxnId": "", "Manufacturer": "", "Model": "", "DeviceId": "", "AppId": "" },
  CCMPTX000015Rq: { "TxnId": "", "ChannelId": "", "TxnNo": "", "ValueDate": "", "AuthLevel": "", "Action": "", "Reason": "", "UserPIN": "", "UserPINE2EE": "", "SignValue": "", "AuthType": "", "OverDueDate": "" },
  CCMPTX000044Rq: { "TxnId": "" },
  CCMPTX000075Rq: { "TxnId": "" },
  CCMPTX000174Rq: { "TxnId": "" ,"ProductParaInfoList":[]},
  CCMPTX000178Rq: { "TxnId": "" },
  CCMPTX000179Rq: { "TxnId": "", "ParaModList": [] },
  CCMPTX000180Rq: { "TxnId": "", "Currency": "", "Country": "", "CustomerId": "", "AcctNo": "", "AcctCur": "", "TrnType": "", "DateFrom": "", "DateTo": "" },
  CCMPTX000183Rq: { "TxnId": "", "Currency": "" },
  CCMPTX000184Rq: { "TxnId": "", "Country": "", "CustomerId": "", "AcctNo": "", "AcctCur": "" },
  CCMPTX000185Rq1: { "TxnId": "" },
  CCMPTX000185Rq2: { "TxnId": "" },
  CCMPTX000186Rq: { "TxnId": "", "Id": "" },
  CCMPTX000187Rq: { "TxnId": "", "Currency": "" },
  CCMPTX000188Rq: { "TxnId": "", "Currency": "" },
  CCMPTX000189Rq: { "TxnId": "", "Country": "", "CustomerId": "", "AcctNo": "", "AcctCur": "" },
  CCMPTX000200Rq: { "TxnId": "", "Currency": "", "Country": "", "CustomerId": "", "OBUDBU": "", "AcctNo": "" },
  CCMPTX000182Rq: { "TxnId": "", "Currency": "" },
  CCMPTX000185Rq: { "TxnId": "" },
  CCMPTX000190Rq: { "TxnId": "", "Country": "", "CustomerId": "", "AcctNo": "", "AcctCur": "", "Branch": "", "Status": "", "DateType": "", "DateFrom": "", "DateTo": "" },
  CCMPTX000191Rq: { "TxnId": "", "AcctNo": "", "AcctCur": "", "Date": ""},
  CCMPTX000192Rq: { "TxnId": "" },
  CCMPTX000193Rq: { "TxnId": "" },
  CCMPTX000194Rq: { "TxnId": "" },
  CCMPTX000195Rq: { "TxnId": "", "PayerAcctNo": "", "PayeeAcctNo": "", "DebitCur": "", "CreditCur": "", "Amount": "", "Memo": "", "BankId": "", "TxnType": "", "PeriodType": "", "PeriodValue": "", "DateFrom": "", "DateTo": "", "Signature": "", "TxnDate": "", "TxnAlias": "", "UserPIN": "", "UserPINE2EE": "", "AuthType":"" },
  CCMPTX000196Rq: { "TxnId": "", "PayerAcctNo": "", "PayeeAcctNo": "", "DebitCur": "", "CreditCur": "", "Amount": "", "Memo": "", "BankId": "", "TxnType": "", "PeriodType": "", "PeriodValue": "", "DateFrom": "", "DateTo": "", "BatchId": "", "LastBatchId": "" },
  CCMPTX000197Rq: { "TxnId": "", "BatchId": "", "Signature": "" },
  CCMPTX000199Rq: { "TxnId":"", "LastSeq":"", "LastMaxSeq":"", "Category":"" },
  CCMPTX000201Rq: { "TxnId": "", "Currency": "" },
  CCMPTX000202Rq: { "TxnId": "", "Country": "" },
  CCMPTX000203Rq: { "TxnId": "", "Country": "" },
  CCMPTX000204Rq: { "TxnId": "", "NewUserId": "" },
  CCMPTX000205Rq: { "TxnId": "", "TxnCode": "", "DateFrom": "", "DateTo": "", "TxnStatus": "", "PayerId": "", "PayerAcct": "", "TxnCur": "", "PayeeId": "", "PayeeAcct": "", "TxnNo": "", "CacheId": "", "LastTxnNo": "", "LastTxnCode": ""},
  CCMPTX000206Rq: { "TxnId": "", "Locale": "", "KeyWord": "", "CacheId": "", "FAQId": ""},
  CCMPTX000207Rq: { "TxnId": "" },
  CCMPTX000208Rq: { "TxnId": "", "FileName": "" },
  CCMPTX000209Rq: { "TxnId": "" },
  CCMPTX000210Rq: { "TxnId": "", "Agreement": "", "Content": "" },
  CCMPTX000216Rq: { "TxnId": "", "Country": "" }
};
